/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardTrainingRouteImport } from './routes/dashboard.training'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardResumeRouteImport } from './routes/dashboard.resume'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardInterviewsRouteImport } from './routes/dashboard.interviews'
import { Route as DashboardDsaRouteImport } from './routes/dashboard.dsa'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard.certificates'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutPendingRouteImport } from './routes/checkout.pending'
import { Route as CheckoutFailedRouteImport } from './routes/checkout.failed'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as DashboardDsaSlugRouteImport } from './routes/dashboard.dsa.$slug'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardTrainingRoute = DashboardTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInterviewsRoute = DashboardInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDsaRoute = DashboardDsaRouteImport.update({
  id: '/dsa',
  path: '/dsa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPendingRoute = CheckoutPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutFailedRoute = CheckoutFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardDsaSlugRoute = DashboardDsaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardDsaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
  '/signup': typeof SignupRoute
  '/tracks': typeof TracksRoute
  '/verify': typeof VerifyRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/roles': typeof AdminRolesRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/dsa': typeof DashboardDsaRouteWithChildren
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/dsa/$slug': typeof DashboardDsaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
  '/signup': typeof SignupRoute
  '/tracks': typeof TracksRoute
  '/verify': typeof VerifyRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/roles': typeof AdminRolesRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/dsa': typeof DashboardDsaRouteWithChildren
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/dsa/$slug': typeof DashboardDsaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/process': typeof ProcessRoute
  '/signup': typeof SignupRoute
  '/tracks': typeof TracksRoute
  '/verify': typeof VerifyRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/roles': typeof AdminRolesRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/dsa': typeof DashboardDsaRouteWithChildren
  '/dashboard/interviews': typeof DashboardInterviewsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/dsa/$slug': typeof DashboardDsaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/process'
    | '/signup'
    | '/tracks'
    | '/verify'
    | '/admin/candidates'
    | '/admin/cms'
    | '/admin/payments'
    | '/admin/pipeline'
    | '/admin/roles'
    | '/checkout/failed'
    | '/checkout/pending'
    | '/checkout/success'
    | '/dashboard/billing'
    | '/dashboard/certificates'
    | '/dashboard/dsa'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/profile'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/dashboard/training'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/dsa/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/process'
    | '/signup'
    | '/tracks'
    | '/verify'
    | '/admin/candidates'
    | '/admin/cms'
    | '/admin/payments'
    | '/admin/pipeline'
    | '/admin/roles'
    | '/checkout/failed'
    | '/checkout/pending'
    | '/checkout/success'
    | '/dashboard/billing'
    | '/dashboard/certificates'
    | '/dashboard/dsa'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/profile'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/dashboard/training'
    | '/admin'
    | '/dashboard'
    | '/dashboard/dsa/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/process'
    | '/signup'
    | '/tracks'
    | '/verify'
    | '/admin/candidates'
    | '/admin/cms'
    | '/admin/payments'
    | '/admin/pipeline'
    | '/admin/roles'
    | '/checkout/failed'
    | '/checkout/pending'
    | '/checkout/success'
    | '/dashboard/billing'
    | '/dashboard/certificates'
    | '/dashboard/dsa'
    | '/dashboard/interviews'
    | '/dashboard/jobs'
    | '/dashboard/profile'
    | '/dashboard/resume'
    | '/dashboard/settings'
    | '/dashboard/training'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/dsa/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProcessRoute: typeof ProcessRoute
  SignupRoute: typeof SignupRoute
  TracksRoute: typeof TracksRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/training': {
      id: '/dashboard/training'
      path: '/training'
      fullPath: '/dashboard/training'
      preLoaderRoute: typeof DashboardTrainingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/interviews': {
      id: '/dashboard/interviews'
      path: '/interviews'
      fullPath: '/dashboard/interviews'
      preLoaderRoute: typeof DashboardInterviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dsa': {
      id: '/dashboard/dsa'
      path: '/dsa'
      fullPath: '/dashboard/dsa'
      preLoaderRoute: typeof DashboardDsaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/pending': {
      id: '/checkout/pending'
      path: '/pending'
      fullPath: '/checkout/pending'
      preLoaderRoute: typeof CheckoutPendingRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/failed': {
      id: '/checkout/failed'
      path: '/failed'
      fullPath: '/checkout/failed'
      preLoaderRoute: typeof CheckoutFailedRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/dsa/$slug': {
      id: '/dashboard/dsa/$slug'
      path: '/$slug'
      fullPath: '/dashboard/dsa/$slug'
      preLoaderRoute: typeof DashboardDsaSlugRouteImport
      parentRoute: typeof DashboardDsaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutFailedRoute: typeof CheckoutFailedRoute
  CheckoutPendingRoute: typeof CheckoutPendingRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutFailedRoute: CheckoutFailedRoute,
  CheckoutPendingRoute: CheckoutPendingRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface DashboardDsaRouteChildren {
  DashboardDsaSlugRoute: typeof DashboardDsaSlugRoute
}

const DashboardDsaRouteChildren: DashboardDsaRouteChildren = {
  DashboardDsaSlugRoute: DashboardDsaSlugRoute,
}

const DashboardDsaRouteWithChildren = DashboardDsaRoute._addFileChildren(
  DashboardDsaRouteChildren,
)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardDsaRoute: typeof DashboardDsaRouteWithChildren
  DashboardInterviewsRoute: typeof DashboardInterviewsRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTrainingRoute: typeof DashboardTrainingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardDsaRoute: DashboardDsaRouteWithChildren,
  DashboardInterviewsRoute: DashboardInterviewsRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTrainingRoute: DashboardTrainingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProcessRoute: ProcessRoute,
  SignupRoute: SignupRoute,
  TracksRoute: TracksRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
